
#ifndef FIBERENDPOINTFROMLABELMAPLIB_EXPORT_H
#define FIBERENDPOINTFROMLABELMAPLIB_EXPORT_H

#ifdef FIBERENDPOINTFROMLABELMAPLIB_STATIC_DEFINE
#  define FIBERENDPOINTFROMLABELMAPLIB_EXPORT
#  define FIBERENDPOINTFROMLABELMAPLIB_TEMPLATE_EXPORT
#  define FIBERENDPOINTFROMLABELMAPLIB_NO_EXPORT
#else
#  ifndef FIBERENDPOINTFROMLABELMAPLIB_EXPORT
#    ifdef FiberEndPointFromLabelMapLib_EXPORTS
        /* We are building this library */
#      define FIBERENDPOINTFROMLABELMAPLIB_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define FIBERENDPOINTFROMLABELMAPLIB_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef FIBERENDPOINTFROMLABELMAPLIB_TEMPLATE_EXPORT
#    ifdef FiberEndPointFromLabelMapLib_EXPORTS
        /* We are building this library */
#      define FIBERENDPOINTFROMLABELMAPLIB_TEMPLATE_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define FIBERENDPOINTFROMLABELMAPLIB_TEMPLATE_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef FIBERENDPOINTFROMLABELMAPLIB_NO_EXPORT
#    define FIBERENDPOINTFROMLABELMAPLIB_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED
#  define FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED_EXPORT
#  define FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED_EXPORT FIBERENDPOINTFROMLABELMAPLIB_EXPORT FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED
#endif

#ifndef FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED_NO_EXPORT
#  define FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED_NO_EXPORT FIBERENDPOINTFROMLABELMAPLIB_NO_EXPORT FIBERENDPOINTFROMLABELMAPLIB_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define FIBERENDPOINTFROMLABELMAPLIB_NO_DEPRECATED
#endif

#endif
